// <auto-generated />
namespace RaysHotDogApp.WebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedseedchangedpkhdgaddedfkhd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedseedchangedpkhdgaddedfkhd));
        
        string IMigrationMetadata.Id
        {
            get { return "201707161834414_changed-seed-changed-pk-hdg-added-fk-hd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
