// <auto-generated />
namespace RaysHotDogApp.WebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hackishwaytofixproblem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hackishwaytofixproblem));
        
        string IMigrationMetadata.Id
        {
            get { return "201707161916260_hackish-way-to-fix-problem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
