// <auto-generated />
namespace RaysHotDogApp.WebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hopefullyautoincrementworksnowpls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hopefullyautoincrementworksnowpls));
        
        string IMigrationMetadata.Id
        {
            get { return "201707161854271_hopefully-autoincrement-works-now-pls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
